name: Deploy to AWS ASG

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID:      ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY:  ${{secrets.AWS_SECRET_ACCESS_KEY}}

    outputs:
      output1: ${{ steps.instance_ip.outputs.test}}

    steps:
      - name: Install awscli
        run: sudo apt install awscli -y

      - name: configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          
      - name: Store instance-id  in variable
        run: instance_id=$(aws ec2 run-instances --image-id ami-0c9a52690acf91d95 --key-name mumbai-key --instance-type t2.micro --query 'Instances[*].[InstanceId]' --output text) && sleep 50

      - name: Pull artifacts from S3 bucket
        run: aws s3 cp s3://bucket-for-tfstate-remote/medi-html.zip medi-html.zip
          
      - name: Store instance-ip in variable
        run: |
          aws ec2 describe-instances --instance-ids $instance_id --query 'Reservations[*].Instances[*].[PublicIpAddress]'  --output text > ip.txt

          echo "IP=$(cat ip.txt)" >> $GITHUB_ENV
          env
          
      # - name: print ip
      #   run: echo ip.txt

      # - name: Create output of $instance-ip
      #   id: instance_ip
      #   run: |  
      #     echo -n "::set-output name=test::ip.txt"
        
      - name: copy artifacts to instance via ssh key
        # env:
        #   HOST: $(cat ip.txt)
        uses: appleboy/scp-action@master
        with:
          host: ${{env.IP}}
          username: ubuntu
          key: ${{ secrets.KEY }}
          source: 'medi-html.zip'
          port: 22
          target: '/home/ubuntu/'
  
      # - name: run commands on a remote server
      #   uses: fifsky/ssh-action@master
      #   with:
      #     command: |
      #       sudo apt update -y
      #       sudo apt install unzip -y
      #       unzip medi-html.zip
      #       cd medi-html
      #       sudo cp -R ~/medi-html/* /var/www/html/
      #     host: $ip.txt
      #     user: ubuntu
      #     key: ${{ secrets.KEY}}








































      # - name: Create AMI of instance
      #   run: ami_id=$(aws ec2 create-image --instance-id $instance_id --name "new-AMI" --description "new AMi with updated artifacts" --query ImageId --output text)



#aws ec2 create-image --instance-id i-0bec1602ac4ae0f85 --name new_updated_ami

#